version: '3'

services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: unless-stopped

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: obstructions
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
